# https://github.com/probot/settings

branches:
  - name: "master"

    # https://docs.github.com/en/rest/reference/repos#delete-branch-protection
    # https://docs.github.com/en/rest/reference/repos#update-branch-protection

    protection:
      enforce_admins: null
      required_linear_history: false
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
      required_status_checks:
        checks:
          - context: "Coding Standards"
        strict: false
      restrictions: null

# https://docs.github.com/en/rest/reference/issues#create-a-label
# https://docs.github.com/en/rest/reference/issues#update-a-label

labels:
  - name: "bug"
    color: "ee0701"

  - name: "dependency"
    color: "0366d6"

  - name: "enhancement"
    color: "0e8a16"

  - name: "question"
    color: "cc317c"

  - name: "security"
    color: "ee0701"

  - name: "stale"
    color: "eeeeee"

# https://docs.github.com/en/rest/reference/repos#update-a-repository

repository:
  allow_merge_commit: true
  allow_rebase_merge: false
  allow_squash_merge: false
  archived: false
  default_branch: "master"
  delete_branch_on_merge: true
  description: "Provides default community health files for @Lctrs repositories."
  enable_automated_security_fixes: false
  enable_vulnerability_alerts: false
  has_downloads: false
  has_issues: false
  has_pages: false
  has_projects: false
  has_wiki: false
  name: ".github"
  private: false

  # https://docs.github.com/en/rest/reference/repos#replace-all-repository-topics

  topics: ""
