# https://docs.github.com/en/actions

name: "Integrate"

on: # yamllint disable-line rule:truthy
  pull_request: null
  push:
    branches:
      - "master"

jobs:
  coding-standards:
    name: "Coding Standards"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac" # v4.0.0

      - name: "Lint YAML files"
        uses: "ibiqlik/action-yamllint@v3.1.1"
        with:
          config_file: ".yamllint.yaml"
          file_or_dir: "."
          strict: true
